# Use Node.js LTS version
FROM node:22-slim

# Set working directory
WORKDIR /inventpedia/frontend

# Copy package.json and install dependencies
COPY package.json package-lock.json ./

RUN npm install

# Copy frontend source code
COPY . .

# Build the Next.js app
RUN npm run build

# Expose port
EXPOSE 3000

# Define environment variable
# ENV NODE_ENV=production

# Start Next.js
CMD ["npm", "run", "start"]
