# Use Node.js LTS version
FROM node:22-slim

# Set working directory
WORKDIR /inventpedia/server

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy backend source code
COPY . .

# Build TypeScript code
RUN npm run build

# Expose port
EXPOSE 4000

# Start the server
CMD ["node", "dist/index.js"]
